txn:
  mappings:
    PAYMENT:
      transaction:
        TXN_TYPE:
          source: constant
          value: PAYMENT
          required: true

        AMOUNT:
          source: json
          path: $.amount
          required: true

        CURRENCY:
          source: json
          path: $.currency
          required: true

        SOURCE_SYSTEM:
          source: json
          path: $.sourceSystem
          required: true

      transactionDetails:
        - column: CUSTOMER_ID
          source: json
          path: $.customerId
          required: true

      addresses:
        definitions:
          - jsonPath: $.billingAddress
            addressType: BILLING

      status:
        initial:
          current_status: ACCEPTED
          remarks: Created in system
